apiVersion: v1
kind: ReplicationController
metadata:
  name: jenkins
  labels:
    name: jenkins-test-rc
spec:
  replicas: 1
  selector:
    app: jenkins-test-rc
  template:
    metadata:
      name: jenkins
      labels:
        app: jenkins-test-rc
    spec:
      containers:
      - name: jenkins
        image: jenkins
        ports:
        - containerPort: 80
